# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.network "private_network", ip: "192.168.33.44", auto_config: false
  config.vm.provision 'shell', inline: "ifconfig enp0s8 192.168.33.44", run: "always"

  config.ssh.forward_env = []

  config.vm.provision "ansible" do |ansible|
    ansible.compatibility_mode = "2.0"
    ansible.playbook = "playbook.yml"
    ansible.become = true
  end
end
